name: 'Close Stale Issues'
description: 'Close issues and pull requests with no recent activity'
author: 'GitHub'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.'
    required: false
    default: ${{ github.token }}
  feedback-message:
    description: 'The message to post on the pr.'
    required: false
  days-before-feedback:
    description: 'The number of days old an issue or a pull request can be before marking it stale. Set to -1 to never mark issues or pull requests as stale automatically.'
    required: false
    default: '60'
  feedback-label:
    description: 'The label to apply when an issue has been commented on.'
    required: false
    default: 'feedback-requested'
  debug-only:
    description: 'Run the processor in debug mode without actually performing any operations on live issues.'
    default: 'false'
    required: false
  operations-per-run:
    description: 'The maximum number of operations per run, used to control rate limiting (GitHub API CRUD related).'
    default: '30'
    required: false
  start-date:
    description: 'The date used to skip the stale action on issue/pull request created before it (ISO 8601 or RFC 2822).'
    default: ''
    required: false
  exempt-draft-pr:
    description: 'Exempt draft pull requests from being marked as stale. Default to false.'
    default: 'false'
    required: false
  enable-statistics:
    description: 'Display some statistics at the end regarding the stale workflow (only when the logs are enabled).'
    default: 'true'
    required: false
  exempt-labels:
    description: 'The labels that mean a pr is exempt from asking for feedback. Separate multiple labels with commas (eg. "label1,label2").'
    default: ''
    required: false
  exempt-authors:
    description: 'The authors which exempt a pull request from being asked for feedback. Separate multiple authors with commas (eg. "user1,user2").'
    default: ''
    required: false
  exempt-bots:
    description: 'Whether bots are exempt from being asked for feedback.'
    default: ''
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
